[package]
name = "gst-plugin"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
categories = ["multimedia"]
description = "Infrastructure for writing GStreamer plugins in Rust"
repository = "https://github.com/sdroege/gst-plugin-rs/tree/master/gst-plugin"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://sdroege.github.io/rustdoc/gst-plugin/gst_plugin/"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]

[dependencies]
libc = "0.2"
lazy_static = "1.0"
byteorder = "1.0"
glib-sys = "0.6"
gobject-sys = "0.6"
gstreamer-sys = "0.5"
gstreamer-base-sys = "0.5"
glib = "0.5"
gstreamer = "0.11"
gstreamer-base = "0.11"

[lib]
name = "gst_plugin"
path = "src/lib.rs"
