[package]
name = "gst-plugin"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
categories = ["multimedia"]
description = "Infrastructure for writing GStreamer plugins in Rust"
repository = "https://github.com/sdroege/gst-plugin-rs/gst-plugin"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://sdroege.github.io/rustdoc/gst-plugin/gst_plugin_rs"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]

[dependencies]
libc = "0.2"
lazy_static = "1.0"
byteorder = "1.0"
glib-sys = "0.5"
gobject-sys = "0.5"
gstreamer-sys = { version = "0.4", features = ["v1_10"] }
gstreamer-base-sys = { version = "0.4", features = ["v1_10"] }
glib = "0.4"
gstreamer = { version = "0.10", features = ["v1_10"] }
gstreamer-base = { version = "0.10" }

[lib]
name = "gst_plugin"
path = "src/lib.rs"
