[package]
name = "gst-plugin-audiofx"
version = "0.6.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MIT/Apache-2.0"
description = "Rust AudioFx Plugin"
edition = "2018"

[dependencies]
glib = { version = "0.10" }
gstreamer = { version = "0.16" }
gstreamer-base = { version = "0.16" }
gstreamer-audio = { version = "0.16" }
byte-slice-cast = "0.3"
num-traits = "0.2"
lazy_static = "1.0"
ebur128 = "0.1"

[lib]
name = "gstrsaudiofx"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dev-dependencies]
gstreamer-check = { version = "0.16" }
gstreamer-app = { version = "0.16" }

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
