[package]
name = "gst-plugin-claxon"
version = "0.6.0"
authors = ["Ruben Gonzalez <rgonzalez@fluendo.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MIT/Apache-2.0"
description = "Claxon FLAC Decoder Plugin"
edition = "2018"

[dependencies]
glib = { version = "0.10" }
gstreamer = { version = "0.16" }
gstreamer-audio = { version = "0.16" }
gstreamer-check = { version = "0.16" }
claxon = { version = "0.4" }
byte-slice-cast = "~0.3.4"
atomic_refcell = "0.1"

[lib]
name = "gstclaxon"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
