[package]
name = "gst-plugin-threadshare"
version = "0.6.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
license = "LGPL-2.1-or-later"
description = "Threadshare Plugin"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
edition = "2018"

[dependencies]
libc = "0.2"
glib-sys = { version = "0.10" }
gobject-sys = { version = "0.10" }
gio-sys = { version = "0.10" }
glib = { version = "0.10" }
gio = { version = "0.9" }
gst = { package = "gstreamer", version = "0.16", features=["v1_10"] }
gst-app = { package = "gstreamer-app", version = "0.16" }
gst-check = { package = "gstreamer-check", version = "0.16" }
gst-net = { package = "gstreamer-net", version = "0.16" }
gst-rtp = { package = "gstreamer-rtp", version = "0.16" }
gstreamer-sys = { version = "0.9" }
pin-project = "0.4"
once_cell = "1"
tokio = { git = "https://github.com/fengalin/tokio", tag = "tokio-0.2.13-throttling", features = ["io-util", "macros", "rt-core", "sync", "stream", "time", "tcp", "udp", "rt-util"] }
futures = { version = "0.3", features = ["thread-pool"] }
lazy_static = "1.0"
rand = "0.7"
socket2 = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winsock2", "processthreadsapi"] }

[target.'cfg(unix)'.dependencies]
socket2 = { version = "0.3", features = ["reuseport"] }

[lib]
name = "gstthreadshare"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[example]]
name = "benchmark"
path = "examples/benchmark.rs"

[[example]]
name = "udpsrc-benchmark-sender"
path = "examples/udpsrc_benchmark_sender.rs"

[[example]]
name = "tcpclientsrc-benchmark-sender"
path = "examples/tcpclientsrc_benchmark_sender.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
cc = "1.0.38"
pkg-config = "0.3.15"
