[default.extend-words]
ND = "ND" # net/ndi
encrypter = "encrypter"
numer = "numer" # numerator
paeth = "paeth"
seeked = "seeked"

# mux/mp4
fiel = "fiel"
trun = "trun"

# net/rtp/src/ac3 - "5/8ths" - not sure how to allow this without also letting through all typos of 'this'
ths = "ths"

# net/aws
ines = "ines"
Ines = "Ines"

# net/hlsmultivariantsink
cros = "cros"
ue = "ue"

[files]
extend-exclude = [
    "*.mcc",
    "*.ref",
    "*.scc",
    "net/webrtc/gstwebrtc-api/src/keysyms.js",
    # third party code
    "video/closedcaption/src/c/*",
    "net/webrtc/gstwebrtc-api/third-party/*",
]
