[package]
name = "gst-plugin-simple"
version = "0.1.2"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/gst-plugin-rs"
license = "MIT/Apache-2.0"

[dependencies]
url = "1.1"
glib = "0.4"
gst-plugin = { version = "0.1", path="../gst-plugin" }
gstreamer = "0.10"
gstreamer-base = "0.10"

[lib]
name = "gst_plugin_simple"
path = "src/lib.rs"
