[package]
name = "gst-plugin-fallbackswitch"
version = "0.6.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "LGPL-2.1-or-later"
edition = "2018"
description = "Fallback Switcher Plugin"

[dependencies]
libc = { version = "0.2", optional = true }
glib = { version = "0.10" }
glib-sys = { version = "0.10", optional = true }
gobject-sys = { version = "0.10", optional = true }
gst = { package = "gstreamer", version = "0.16", features = ["v1_14"] }
gst-base = { package = "gstreamer-base", version = "0.16", features = ["v1_16"] }
gst-sys = { package = "gstreamer-sys", version = "0.9", optional = true }
gst-audio = { package = "gstreamer-audio", version = "0.16", features = ["v1_14"] }
gst-video = { package = "gstreamer-video", version = "0.16", features = ["v1_14"] }
gtk = { version = "0.9", optional = true }
gio = { version = "0.9", optional = true }
once_cell = "1.0"

[dev-dependencies]
gst-app = { package = "gstreamer-app", version = "0.16",  features = ["v1_14"]}
gst-check = { package = "gstreamer-check", version = "0.16",  features = ["v1_14"]}

[lib]
name = "gstfallbackswitch"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[example]]
name = "gtk-fallbackswitch"
path = "examples/gtk_fallbackswitch.rs"
required-features = ["gtk", "gio"]

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
cc = "1.0"
pkg-config = "0.3"

[features]
default = ["glib-sys", "gobject-sys", "gst-sys", "libc"]
#v1_18 = ["gstreamer-base/v1_18"]
