[package]
name = "gst-plugin-cdg"
version = "0.6.0"
authors = ["Guillaume Desmottes <guillaume.desmottes@collabora.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MIT/Apache-2.0"
description = "CDG Plugin"
edition = "2018"

[dependencies]
glib = { version = "0.10" }
gstreamer = { version = "0.16", features = ["v1_12"] }
gstreamer-base = { version = "0.16", features = ["v1_12"] }
gstreamer-video = { version = "0.16", features = ["v1_12"] }
gstreamer-app = { version = "0.16" }
cdg = "0.1"
cdg_renderer = "0.5"
image = "0.23"
muldiv = "0.2"
lazy_static = "1.0"

[lib]
name = "gstcdg"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
