[package]
name = "gst-plugin-http"
version = "0.4.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MIT/Apache-2.0"

[dependencies]
url = "1.1"
glib = { version = "0.7", features = ["subclassing"] }
reqwest = "0.9"
hyperx = "0.14"
gstreamer = { version = "0.13", features = ["subclassing"] }
gstreamer-base = { version = "0.13", features = ["subclassing"] }

[lib]
name = "gstrshttp"
crate-type = ["cdylib"]
path = "src/lib.rs"
