[package]
name = "gst-plugin-togglerecord"
version = "0.6.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
license = "LGPL-2.1-or-later"
description = "Toggle Record Plugin"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
edition = "2018"

[dependencies]
glib = { version = "0.10" }
gstreamer = { version = "0.16" }
gstreamer-audio = { version = "0.16" }
gstreamer-video = { version = "0.16" }
gtk = { version = "0.9", optional = true }
gio = { version = "0.9", optional = true }
parking_lot = "0.11"
lazy_static = "1.0"

[dev-dependencies]
either = "1.0"

[lib]
name = "gsttogglerecord"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[example]]
name = "gtk-recording"
path = "examples/gtk_recording.rs"
required-features = ["gtk", "gio"]

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
