[package]
name = "gst-plugin-csound"
version = "0.6.0"
authors = ["Natanael Mojica <neithanmo@gmail.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "LGPL-2.1-or-later"
edition = "2018"
description = "An Audio filter plugin based on Csound"

[dependencies]
glib = { version = "0.10" }
gst = { package = "gstreamer", version = "0.16" }
gst_base = { package = "gstreamer-base", version = "0.16" }
gst_audio = { package = "gstreamer-audio", version = "0.16" }
gst_check = { package = "gstreamer-check", version = "0.16" }
csound = "0.1.8"
once_cell = "1.0"
byte-slice-cast = "0.3"

[lib]
name = "gstcsound"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[example]]
name = "csound-effect"
path = "examples/effect_example.rs"

[build-dependencies]
gst-plugin-version-helper = { path = "../../version-helper", version = "0.2" }
