[package]
name = "gst-plugin-togglerecord"
version = "0.2.1"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
license = "LGPL-2.1+"

[dependencies]
glib = "0.5"
gstreamer = "0.11"
gstreamer-video = "0.11"
gst-plugin = { version = "0.2", path = "../gst-plugin" }
gtk = { version = "0.4", features = ["v3_6"], optional = true }
gio = { version = "0.4", optional = true }
send-cell = { version = "0.1", optional = true }

[dev-dependencies]
either = "1.0"

[lib]
name = "gsttogglerecord"
crate-type = ["cdylib"]
path = "src/lib.rs"

[[example]]
name = "gtk-recording"
path = "examples/gtk_recording.rs"
required-features = ["gtk", "gio", "send-cell"]

