[package]
name = "gst-plugin-lewton"
version = "0.6.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MIT/Apache-2.0"
description = "lewton Vorbis Decoder Plugin"
edition = "2018"

[dependencies]
glib = { version = "0.10" }
gstreamer = { version = "0.16" }
gstreamer-audio = { version = "0.16" }
gstreamer-check = { version = "0.16" }
lewton = { version = "0.10", default-features = false }
byte-slice-cast = "0.3"
atomic_refcell = "0.1"
lazy_static = "1.0"

[lib]
name = "gstlewton"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
