[package]
name = "gst-plugin-textwrap"
version = "0.6.0"
authors = ["Mathieu Duponchelle <mathieu@centricular.com>"]
license = "LGPL-2.1-or-later"
edition = "2018"
description = "Rust Text Wrap Plugin"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"

[dependencies]
glib = { version = "0.10" }
once_cell = "1.0"
textwrap = { version = "0.12", features = ["hyphenation"] }
hyphenation = "0.8"

[dependencies.gst]
version = "0.16"
features = ["v1_12"]
package="gstreamer"

[lib]
name = "gstrstextwrap"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }

[dev-dependencies.gst-check]
version = "0.16"
package="gstreamer-check"
