[package]
name = "gst-plugin-flv"
version = "0.3.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugin-rs"
license = "MIT/Apache-2.0"

[dependencies]
url = "1.1"
gst-plugin = { version = "0.3", path="../gst-plugin" }
gst-plugin-simple = { version = "0.3", path="../gst-plugin-simple" }
gstreamer = "0.12"
num-rational = { version = "0.2", default-features = false, features = [] }
nom = "3.0"
flavors = {git = "https://github.com/rust-av/flavors.git"}
muldiv = "0.2"

[lib]
name = "gstrsflv"
crate-type = ["cdylib"]
path = "src/lib.rs"
