[package]
name = "gst-plugin-rav1e"
version = "0.6.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MIT/Apache-2.0"
description = "rav1e AV1 Encoder Plugin"
edition = "2018"

[dependencies]
glib = { version = "0.10" }
gstreamer = { version = "0.16" }
gstreamer-video = { version = "0.16", features = ["v1_12"] }
gstreamer-check = { version = "0.16" }
rav1e = { version = "0.3", default-features = false }
atomic_refcell = "0.1"
lazy_static = "1.0"

[lib]
name = "gstrav1e"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
