[package]
name = "gst-plugin-closedcaption"
version = "0.6.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>", "Jordan Petridis <jordan@centricular.com>"]
license = "LGPL-2.1-or-later"
edition = "2018"
description = "Rust Closed Caption Plugin"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"

[dependencies]
glib = { version = "0.10" }
combine = "4.0"
either = "1"
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"
lazy_static = "1.2"
atomic_refcell = "0.1"
cairo-rs = { version = "0.9", features=["use_glib"] }
cairo-sys-rs = { version = "0.10" }
pango = { version = "0.9" }
pangocairo = { version = "0.10" }

[dependencies.gst]
version = "0.16"
features = ["v1_16"]
package="gstreamer"

[dependencies.gst-base]
version = "0.16"
features = ["v1_16"]
package="gstreamer-base"

[dependencies.gst-video]
version = "0.16"
features = ["v1_16"]
package="gstreamer-video"

[dev-dependencies]
pretty_assertions = "0.6"
rand = { version = "0.7", features = ["small_rng"] }

[dev-dependencies.gst-check]
version = "0.16"
package="gstreamer-check"

[lib]
name = "gstrsclosedcaption"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper", version = "0.2" }
cc = "1.0"
