[package]
name = "gst-plugin-tutorial"
version = "0.4.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MIT/Apache-2.0"

[dependencies]
glib = { version = "0.7", features = ["subclassing"] }
gstreamer = { version = "0.13", features = ["subclassing"] }
gstreamer-base = { version = "0.13", features = ["subclassing"] }
gstreamer-video = { version = "0.13" }
gstreamer-audio = { version = "0.13" }
byte-slice-cast = "0.2"
num-traits = "0.2"

[lib]
name = "gstrstutorial"
crate-type = ["cdylib"]
path = "src/lib.rs"
