[package]
name = "gst-plugin-tutorial"
version = "0.2.1"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/gst-plugin-rs"
license = "MIT/Apache-2.0"

[dependencies]
gst-plugin = { version = "0.2", path="../gst-plugin" }
glib = "0.5"
gstreamer = "0.11"
gstreamer-base = "0.11"
gstreamer-video = "0.11"
gstreamer-audio = "0.11"
byte-slice-cast = "0.1"
num-traits = "0.2"

[lib]
name = "gstrstutorial"
crate-type = ["cdylib"]
path = "src/lib.rs"
