[package]
name = "gst-plugin-file"
version = "0.2.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/gst-plugin-rs"
license = "MIT/Apache-2.0"

[dependencies]
url = "1.1"
gst-plugin = { version = "0.2", path="../gst-plugin" }
gst-plugin-simple = { version = "0.2", path="../gst-plugin-simple" }
gstreamer = "0.11"

[lib]
name = "gstrsfile"
crate-type = ["cdylib"]
path = "src/lib.rs"
