[package]
name = "gst-plugin-audiofx"
version = "0.3.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/gst-plugin-rs"
license = "MIT/Apache-2.0"

[dependencies]
gobject-subclass = "0.2"
gst-plugin = { version = "0.3", path="../gst-plugin" }
glib = "0.6"
gstreamer = "0.12"
gstreamer-base = "0.12"
gstreamer-audio = "0.12"
byte-slice-cast = "0.2"
num-traits = "0.2"

[lib]
name = "gstrsaudiofx"
crate-type = ["cdylib"]
path = "src/lib.rs"
